#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
   
    # get screen_name's tweets
    tweets = helpers.get_user_timeline(sys.argv[1][1::])
   
    if tweets == None:
        sys.exit("The user name doesn't exist or this is a private account")
     
    for tweet in tweets[0:50]:
       
        # analyze tweet
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print("", colored(score, "green"), "", end="")
            print(colored(tweet, "green"))
        elif score < 0.0:
            print(colored(score, "red"), "", end="")
            print(colored(tweet, "red"))
        else:
            print("", colored(score, "yellow"), "", end="")
            print(colored(tweet, "yellow"))

if __name__ == "__main__":
    main()
